# Generated by Django 5.0.4 on 2024-05-11 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelOwner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking_app.user')),
                ('owner_exp_status', models.IntegerField(null=True)),
            ],
            bases=('booking_app.user',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking_app.user')),
                ('guest_rating', models.IntegerField(null=True)),
            ],
            bases=('booking_app.user',),
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('detail', models.CharField(max_length=200, null=True)),
                ('owners', models.ManyToManyField(related_name='hobbies', to='booking_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('id_card_number', models.ImageField(null=True, upload_to='')),
                ('serial', models.CharField(max_length=30, null=True)),
                ('person_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='booking_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('address', models.CharField(max_length=40, null=True)),
                ('stars', models.IntegerField(null=True)),
                ('rating', models.FloatField(null=True)),
                ('owners', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='booking_app.hotelowner')),
            ],
        ),
        migrations.CreateModel(
            name='PersonComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, null=True)),
                ('comment_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('person_rating', models.PositiveIntegerField(null=True)),
                ('hotels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_comments', to='booking_app.hotel')),
                ('persons', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_comments', to='booking_app.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HotelsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, null=True)),
                ('comment_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('hotel_rating', models.PositiveIntegerField(null=True)),
                ('hotels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_comments', to='booking_app.hotel')),
                ('persons', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_comments', to='booking_app.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=200, null=True)),
                ('book_time', models.DateTimeField(auto_now_add=True)),
                ('hotels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_info', to='booking_app.hotel')),
                ('persons', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_info', to='booking_app.person')),
            ],
        ),
    ]
