# Generated by Django 5.0.4 on 2024-05-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_card_number',
            field=models.IntegerField(null=True),
        ),
    ]
