# Generated by Django 5.0.4 on 2024-05-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_alter_profile_id_card_number'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['address'], name='address_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['stars'], name='stars_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_name', 'first_name'], name='last_first_name_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name'], name='first_name_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_name'], name='last_name_idx'),
        ),
    ]
