# Generated by Django 5.0.4 on 2024-06-09 15:31

import booking_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_alter_profile_id_card_number_alter_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinfo',
            options={'verbose_name_plural': 'Book Info'},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name_plural': 'Booking'},
        ),
        migrations.AlterModelOptions(
            name='hobby',
            options={'verbose_name_plural': 'Hobby'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name_plural': 'Hotel'},
        ),
        migrations.AlterModelOptions(
            name='hotelowner',
            options={'verbose_name_plural': 'Hotel Owner'},
        ),
        migrations.AlterModelOptions(
            name='hotelscomment',
            options={'verbose_name_plural': 'Hotels Comment'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'Person'},
        ),
        migrations.AlterModelOptions(
            name='personcomment',
            options={'verbose_name_plural': 'Person comment'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profile'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name_plural': 'Room'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'User'},
        ),
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.IntegerField(null=True, validators=[booking_app.validators.validate_hotel_stars]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(validators=[booking_app.validators.validate_user_age]),
        ),
    ]
