# Generated by Django 5.0.4 on 2024-06-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0005_alter_bookinfo_options_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='photo',
            field=models.ImageField(null=True, upload_to='hotels_photo/'),
        ),
    ]
