# Generated by Django 5.0.4 on 2024-06-16 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0007_personqueue_alter_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personqueue',
            old_name='queue',
            new_name='value',
        ),
    ]
